### ISSUE TITLE
No need redirecting in running test.js

### ISSUE THREAD

**Issue by ghost** [Leaflet/Leafdoc#11]
README.md says

```
js test.js > leafdoc.html
```

`> leafdoc.html` is unnecessary because of `sander.writeFileSync('Leafdoc.html', out);`.

Question:
Does `js` mean SpiderMonkey here? I think leafdoc is supposed to run with Node.js.

**Comment by IvanSanchez** [comment]
> `leafdoc.html` is unnecessary because of `sander.writeFileSync('Leafdoc.html', out);`.

You're welcome to fix it in a pull request.

> Does `js` mean SpiderMonkey here? I think leafdoc is supposed to run with Node.js.

`js` is your javascript shell. I expect node to run and haven't tried other engines. In case of incompatibility, please amend the `package.json` to reflect that.

**Comment by aoyama-val** [comment]
I'm lazy to do pull request.

As `js` is the name of the SpiderMonkey's shell, it might be misleading.

Have you seen my last comment in this issue? In fact, `leadDirective` is not working with my Node 5.1.0.
https://github.com/IvanSanchez/Leafdoc/issues/10

**Comment by IvanSanchez** [comment]
I replaced `test.js` with `jasmine` tests. I think this no longer applies.
