### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by bjorngi** [Leaflet/Leafdoc#13]
> See [Leafdoc's documentation as generated by Leafdoc](http://ivansanchez.github.io/Leafdoc/doc.html), or a test of [partial Leaflet documentation as generated by Leafdoc](http://ivansanchez.github.io/Leafdoc/Leaflet-docs.html).

**Comment by IvanSanchez** [comment]
Plz submit a pull req fixing this ;-)

**Comment by bjorngi** [comment]
I don't know where this links should point. I just know they are dead.

**Comment by IvanSanchez** [comment]
The repo was moved from ivansanchez/Leafdoc to Leaflet/Leafdoc, so the links change from ivansanchez.github.io/Leafdoc to leaflet.github.io/Leafdoc

**Comment by mourner** [comment]
@IvanSanchez both don't work ;)

**Comment by IvanSanchez** [comment]
@mourner @bjorngi [Yes](http://leaflet.github.io/Leafdoc/doc.html) they [do](http://leaflet.github.io/Leafdoc/Leaflet-docs.html) :-P
