### ISSUE TITLE
@constructor vs @factory

### ISSUE THREAD

**Issue by nathancahill** [Leaflet/Leafdoc#15]
Most leaflet classes have a factory function (@factory) that outputs to the Creation section of the class. Can we add @constructor functions there too? Some classes only have constructors, so their docs are missing.

**Comment by nathancahill** [comment]
This is what I have in mind, for something like L.Draggable that only has a @constructor:

![Screenshot](https://cloud.githubusercontent.com/assets/1383872/14763385/482c1cc8-0951-11e6-97c3-b35b85ab4885.png)

And potentially for classes that use both @factory and @constructor?

![Screenshot](https://cloud.githubusercontent.com/assets/1383872/14763426/9e327daa-0952-11e6-846f-f2684bb5eaeb.png)

**Comment by mourner** [comment]
I think we eventually want to get rid of all public constructors and have only one way to create instances.

**Comment by nathancahill** [comment]
Makes sense. Would you entertain a pull request that adds factory functions for the couple of classes that are missing them?

**Comment by mourner** [comment]
Yes, we could do that. As far as I remember, I didn't add factories to some classes like L.Draggable because I wasn't even sure they should be exposed publicly in the API as opposed to internal use only. It increases complexity while having no use for most users.

**Comment by IvanSanchez** [comment]
I've added the `constructor` (and as a bonus, the `destructor`) documentables to , with a basic template.

How we document Leaflet is outside of the scope of this bug, though. I do agree with @mourner in that we should only expose (through the docs) the factories we want, and no constructors at all.
