### ISSUE TITLE
Feature Request - Add repeatMode for Polygon Draw

### ISSUE THREAD

**Issue by bbehling** [Leaflet/Leafdoc#28]
https://github.com/Leaflet/Leaflet.draw/wiki/API-Reference#ldrawhandlers

All other shapes have a repeatMode option. Can we get one for polygons as well?

**Comment by IvanSanchez** [comment]
This is the issue tracker for Leafdoc, not for Leaflet.Draw. Please report issues/feature requests in the right repo.
