### ISSUE TITLE
Publish latest version to NPM

### ISSUE THREAD

**Issue by cherniavskii** [Leaflet/Leafdoc#39]
Hi @IvanSanchez ,
I've noticed, that according to package.json, latest Leafdoc version is 1.5.1, but it's not published to NPM (see https://www.npmjs.com/package/leafdoc)

Can you publish it to NPM? Leaflet uses 1.4.1 for now, and there are NPM audit dependencies warnings, which seem to be fixed in 1.5.1

**Comment by jedfong** [comment]
Any progress on this?  I'm trying to fix audit issues as well.

**Comment by cherniavskii** [comment]
Hi @IvanSanchez 
This is a blocker for https://github.com/Leaflet/Leaflet/pull/6892
leafdoc@1.4.1 throws and error on nodejs v12 (current LTS) because of old version of `sander` dependency

**Comment by cherniavskii** [comment]
Was able to workaround issue by bumping `sander` version in `package-lock.json`, but still

**Comment by mondeja** [comment]
Sander was removed as dependency in pull #48, so Leafdoc can bump and be released on NPM and this issue closed.
