### ISSUE TITLE
Can I describe mixins?

### ISSUE THREAD

**Issue by trusktr** [Leaflet/Leafdoc#40]
I'd like to document mixins. Is this possible with Leafdoc?

EDIT: Ah, looks like I'd need to make a custom documentable, `mixin` for example.

**Comment by IvanSanchez** [comment]
I think what you want to do is document your mixin as a `Class`, then "inherit" your mixin. 

IIRC Leafdoc supports multiple inheritance so this shouldn't be a problem.

**Comment by trusktr** [comment]
Oh, nice!
